#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, link (or copy it) to <.git/hooks>.

echo "Running pre-commit unit tests."
npm run test:units
